### ISSUE TITLE
Error while sending data to Notion

### ISSUE THREAD

**Issue by Mrkwtkr** [TomFrankly/pipedream-notion-voice-notes#40]
I was uploading a 30-minute audio file to my Google Drive. It seems like there is an issue with the workflow on rich text chunking, which should be less than 2000 characters.

I've tried twice with the same audio file. Each time, it did incur API costs (about $0.35 totally), but nothing was added to my Notion database.

Here is the details:

APIResponseError
body failed validation: body.children[1].paragraph.rich_text[0].text.content.length should be ≤ `2000`, instead was `2039`. 
    at null.buildRequestError (/pipedream/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/node_modules/.pnpm/@notionhq+client@2.2.13/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/pipedream/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/node_modules/.pnpm/@notionhq+client@2.2.13/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.retry.retries (file:///pipedream/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1747:23)

**Comment by TomFrankly** [comment]
@Mrkwtkr was this a non-English file, or did you set it to translate to a non-English language?

Can you post the full logs from your Logs tab?

**Comment by Mrkwtkr** [comment]
Both. It's a non-English file. The audio is talked in Chinese. I set the `Summary Language (Advanced)`  to Chinese.

Here is the full logs:

[Pipedream log - Notion Voice Notes (Google Drive).txt](https://github.com/TomFrankly/pipedream-notion-voice-notes/files/13275145/Pipedream.log.-.Notion.Voice.Notes.Google.Drive.txt)

**Comment by TomFrankly** [comment]
@Mrkwtkr I've just shipped a much more robust `makeParagraphs()` method that should handle Chinese text more gracefully. It also guarantees each paragraph can be no more than 1,800 characters, so it should prevent this error.

You can update your workflow by following these instructions: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

**Comment by Mrkwtkr** [comment]
Thank you, I just confirmed that it has been fixed.
