### ISSUE TITLE
Still a Problem with Splitting file into chunks

### ISSUE THREAD

**Issue by VirtualKenji** [TomFrankly/pipedream-notion-voice-notes#45]
- I used Dropbox

- I uploaded a new audio file

- I've been subscribed to chatgpt pro for a while

- I added my phone number to my billing address

- Afterwards, I generated a new API key and replaced the old one

My billing address has been working fine the whole time, but I did add my phone number.

Could this be because I am based in Manila?

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/150046027/eb57a3d1-23c5-4405-b646-aa153e83a29f)

at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:242:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:748:28)

**Comment by TomFrankly** [comment]
@VirtualKenji I don't think this is your fault; OpenAI has been having downtime issues over the last few days. Their servers are getting hit really hard right now, both due to a DDOS attack (according to one of their marketing heads on Twitter) and by surge in use due to the new models that launched earlier this week.

I'm betting if you retry a bit later, it should work. As far as I know, there's nothing about your location that should block this workflow!
