### ISSUE TITLE
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI.

### ISSUE THREAD

**Issue by mayorgergich** [TomFrankly/pipedream-notion-voice-notes#47]
```    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/da0675b74e78f05c34811117c0816207386b9ed914b78651fd4d747c1602227f/code/Notion-Voice-Notes.mjs:396:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/da0675b74e78f05c34811117c0816207386b9ed914b78651fd4d747c1602227f/code/Notion-Voice-Notes.mjs:1943:22)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)```

I've ensured that my billing is up to date and added credits to the OpenAI account. I'm using a Business G Drive account and no errors during those steps.

**Comment by TomFrankly** [comment]
@mayorgergich Did your error message also have a "Full error from OpenAI" line on it? It should have, so if you can share that, it'll be helpful!

**Comment by mayorgergich** [comment]
Hi @TomFrankly ! Here is everything from the pipedream page. Unfortunately I don't see the referenced line anywhere.
<img width="881" alt="Screenshot 2023-11-25 at 5 00 19 PM" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/117896074/b9e251bb-bddc-4532-8a4b-9cabcc33bb5d">
<img width="886" alt="Screenshot 2023-11-25 at 5 00 12 PM" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/117896074/9195dc86-0812-4e79-a5c5-f7c653637de8">

**Comment by TomFrankly** [comment]
@mayorgergich thanks for that detail! I think is a generic APIConnectionError from OpenAI, which means it doesn't get a status code but generally means the script was unable to connect to the OpenAI API. This is likely due to factors beyond our control – e.g. issues at OpenAI, or with AWS Lambda (what Pipedream workflows run on).

However, I've gone in and improved the code so that it'll now retry a few times if it hits this generic error. Previously, it would look for a status code before retrying, as I didn't know OpenAI's API had an error type that lacked a status code.

You can update your workflow like so: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

Hopefully this at least reduces the rate of errors like this, since the script will now retry automatically if it hits one!
