### ISSUE TITLE
Error Splitting the File Into Chunks

### ISSUE THREAD

**Issue by sqlcursor** [TomFrankly/pipedream-notion-voice-notes#54]
First and foremost, THANK YOU for this workflow.  I used your previous version and am looking forward to this new version to remove some of the previous challenges around meeting length.  I am currently testing out the new workflow on a 30 minute call and I'm getting the following error:

Error

An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.
Details

    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)
------------

If there is any guidance that you could provide on this I would appreciate it.

This is using Dropbox and the first portion of downloading to a tmp location is working just fine.

**Comment by sqlcursor** [comment]
This ended up being an issue with my existing OpenAI account having a $0.00 balance.  Sorry for the confusion.
