### ISSUE TITLE
APIResponseError during Notion note creation

### ISSUE THREAD

**Issue by babulee** [TomFrankly/pipedream-notion-voice-notes#56]
**Describe the bug**
I uploaded a voice memo of about 2 hours in length and encountered the following error:

APIResponseError
body failed validation: body.children[4].paragraph.rich_text[0].text.content.length should be ≤ `2000`, instead was `3924`. 
    at null.buildRequestError 

I can see in Notion that a new note is created with Summary populated.  But it is missing Transcript, Main Points, Action Items, and References.  Perhaps something is wrong during the import of Transcript? 

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
OneDrive

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update
I am using the latest version

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
During automated runs

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

APIResponseError
body failed validation: body.children[4].paragraph.rich_text[0].text.content.length should be ≤ `2000`, instead was `3924`. 
    at null.buildRequestError (/tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.retry.retries (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1747:23)

**Comment by babulee** [comment]
Sorry, seems like I am running an old version

**Comment by babulee** [comment]
Sorry, seems like I am running an old version

**Comment by TomFrankly** [comment]
@babulee yep, this problem was fixed in the latest update!
