### ISSUE TITLE
How to have a workflow to convert text on notion, at least for test.

### ISSUE THREAD

**Issue by ippo28** [TomFrankly/pipedream-notion-voice-notes#58]
Hello Tom, nicer to write you.
First of all thank you for your astonishing job 😱

**Describe the bug**
I tried  your workflow and unfortunately I haven't been able yet to obtain a notion version of my notes 😓. At first the main problem I think it was the billing issue on openAI, then when everything seemed to be right I had the error about that it was impossible to create the notion page 🤦‍♂️, but maybe from the log I think I figured out how to solve it, let's cross the finger.
I wanted more to ask you if there could be the possibility to test it by starting from a txt file as from openAI page the most expensive part was the transcription from audio, indeed I spent $2,65 doing the tests and $2,50 were for whisper API 😅 as my audio is long 1h30.
I was able to get the txt file from whisper by using google colaborator and for the moment I hadn't to pay for it 🤞
Again thank you very much.
Below I posted the log related to the error I got at the last trial.

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

`Error creating Notion task:     at null.buildRequestError (/tmp/__pdg__/dist/code/f124a850c3f703097b5494bd1efc77777c2efa4db1b6462c7952f47e82001a2f/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/tmp/__pdg__/dist/code/f124a850c3f703097b5494bd1efc77777c2efa4db1b6462c7952f47e82001a2f/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.retry.retries (file:///tmp/__pdg__/dist/code/f124a850c3f703097b5494bd1efc77777c2efa4db1b6462c7952f47e82001a2f/code/Notion-Voice-Notes.mjs:1647:19)
    at Object.createNotionPage (file:///tmp/__pdg__/dist/code/f124a850c3f703097b5494bd1efc77777c2efa4db1b6462c7952f47e82001a2f/code/Notion-Voice-Notes.mjs:1643:5)
    at Object.run (file:///tmp/__pdg__/dist/code/f124a850c3f703097b5494bd1efc77777c2efa4db1b6462c7952f47e82001a2f/code/Notion-Voice-Notes.mjs:2146:30)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)
 {
  name: 'APIResponseError',
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'x-powered-by': [Array],
      'x-notion-request-id': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"Lezione 2B is not a property that exists. AI cost is not a property that exists.","request_id":"26a15df1-00f0-41a9-b15d-cdd8e35a8676"}'
}`

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google drive

Best regards

**Comment by Gerkinfeltser** [comment]
I’ve also felt that the auto-summarize feature is incredibly useful for summarizing just about anything, be it audio or not. As the original poster mentioned, transcription is the priciest part of the process and if we’re dealing with a text article for this workflow, it’s a bit roundabout to convert it to audio and then back to text (which is my current work around).

I wonder if there’s a way for the system to discern whether a file is audio or text and skip the transcription for text files. I’m not entirely sure about the complexity of this, but I really appreciate all the work that’s gone into this so far. I don’t mean to sound ungrateful; I just think this added flexibility could significantly enhance an already fantastic workflow! 😄
