### ISSUE TITLE
Voice notes Dropbox

### ISSUE THREAD

**Issue by DeltaCPA** [TomFrankly/pipedream-notion-voice-notes#64]
**Describe the bug**

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.

DETAILS

Explain
    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:783:28)
openai
$auth
{1}
api_key:
*****
notion
$auth
{3}
oauth_access_token:
*****
oauth_client_id:
*****
oauth_uid:
*****
steps
{ "trigger": { "event": { ".tag": "file", "client_modified": "2024-01-27T17:22:40Z", "content_hash": "936d1dc0f911f97a7b0df073b482bc1907b24462761ae5367cdf291b072da40c", "id": "id:XOpEaOONOnEAAAAAAAAACA", "is_downloadable": true, "link": "https://uc73e1ee685d3293cbad2441c7cc.dl.dropboxusercontent.com/cd/0/get/CMO_1gvyr8YuusNzfek-vYuz6WPZe8wHA_AwzEIu2naXN2lZ8p3AQNVskWoBwlTJi5g73e3hxnVDugLYlYFKrd3hLDR6xld3J_5bR_pEh2___O5oFXVtmx59dJtEbhqtOiOwl6URneJjwQfnq7HmQNelvE5Sg01-i03-kVXaVLNK5A/file", "name": "My recording 4.m4a", "path_display": "/Apps/Easy Voice Recorder/My recording 4.m4a", "path_lower": "/apps/easy voice recorder/my recording 4.m4a", "rev": "60ff0a8f42bf18997a9e3", "server_modified": "2024-01-27T17:22:41Z", "size": 197154 }, "context": { "id": "2baQ96W6mNvHwxlme7LJ1Uf3wPu", "ts": "2024-01-28T14:02:35.468Z", "pipeline_id": null, "workflow_id": "p_BjCYrLy", "deployment_id": "d_V1skW1dW", "source_type": "TRACE", "verified": false, "hops": null, "test": true, "replay": false, "owner_id": "o_1rIlvgW", "platform_version": "3.46.6", "workflow_name": "Notion Voice Notes (Dropbox)", "resume": null, "emitter_id": "dc_lVumlM8", "trace_id": "2baQ96W6mNvHwxlme7LJ1Uf3wPu", "JIT": true, "attachments": {} } } }
summary_options
[ "Summary", "Main Points", "Action Items", "References" ]
databaseID
All Notes [UBCC] – (used for Ultimate Brain)
6981d40a-2601-4ec0-a0e7-3e42216cd0be
noteTitle
Title
noteDuration
Duration (Seconds)
noteCost
AI Cost
noteTag
Type
noteTagValue
AI Transcription
chat_model
gpt-3.5-turbo
advanced_options
false

**Comment by TomFrankly** [comment]
Hi @DeltaCPA - can you confirm if you've tried the fix described in the error text?

Specifically, you need to set up billing here: https://platform.openai.com/account/billing/overview - not with ChatGPT Plus. After that, you need to create a new API key (https://platform.openai.com/api-keys) and use that in the Pipedream workflow.

If you've already tried that, OpenAI may just be overloaded right now. It's hard to tell what the actual problem is when they just send back "Unidentified Connection Error", so that's our best guess! In this case, I'd recommend waiting a while and trying again later.

**Comment by DeltaCPA** [comment]
I do have OpenAI set up properly.  I applied an update and this is the new message.  BTW, I truly appreciate you sharing.  I can imagine it might be frustrating to see people getting errors.
![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/157970347/b3fdde73-65ee-4628-b96d-09bcdb7db69f)

**Comment by TomFrankly** [comment]
@DeltaCPA this is a different error – when you upload a file to Dropbox, they only expose the URL for about 2 hours to allow for external workflows like this. After that, the URL expires, so you have to re-upload the file to try again (I usually rename it slightly - e.g. `audio.mp3 too audio2.mp3`.

This pretty much only ever a problem when you run into another error and have to spend time debugging the workflow.

I'm still working on the original error; you're not the only one seeing it. It's rare, but still frustrating. I'm pretty sure it's just OpenAI rejecting connection attempts because it's overloaded, but I talked with a developer friend yesterday and I have some ideas for how I can improve the code on my end to maybe work around that.

I'll reply again when I know more, hopefully with a workflow update you can apply!

**Comment by TomFrankly** [comment]
Fixed in the latest version: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow
