### ISSUE TITLE
Unable to Successfully Run After Initially Setting Up and Running a Successful Test

### ISSUE THREAD

**Issue by therealrico** [TomFrankly/pipedream-notion-voice-notes#66]
**Describe the bug**
After setting up the workflow via the instructions with dropbox, I was able to run a successful text. However, I was unable to convert any of my audio files, and I can't even run a successful test. I am unsure of what I might have changed that would have impacted this.
 
**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Dropbox

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update
I set it up last night, so I am not sure if that would apply to my problem today. But the simple answer is no.

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
I was never able to run a successful automated run as far as I can tell. During setup, I had a successful test run. but today it failed.

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**
Error
Failed to download file: Response code 410 (Gone)

DETAILS
    at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:331:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1973:5)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:783:28)

Checking that file is under 300mb...
File size is approximately 6.1mb.
File is under the size limit. Continuing...
Checking if the user set languages...
Active_Handle This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: FSReqCallback, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Comment by therealrico** [comment]
I exceeded my daily limit. So I will try tomorrow I guess. But one weird thing I am noticing is that I am showing two accounts for dropbox. No idea if that is making a difference, but I don't really understand why that would be happening or if it is causing an issue.
![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/51206094/7eee8934-dafd-4338-838e-3014c6e817d4)

**Comment by TomFrankly** [comment]
@therealrico these are Sources, I believe: https://pipedream.com/docs/sources/

They're discrete units in Pipedream, but can connect to the same account for whatever tool you're using. Useful if you want to configure multiple connections to the same tool, but with different rules!
