### ISSUE TITLE
Issue with the Database

### ISSUE THREAD

**Issue by Alfrex92** [TomFrankly/pipedream-notion-voice-notes#70]
**Describe the bug**
Everything was going smoothly until I reached the step to select the Notion Database.
![Screenshot 2024-02-15 at 9 50 43 PM](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/22891582/4f559ed3-cc43-48c3-aaf5-eeb174385dee)

In your guide [here](https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#choose-your-notion-database), you suggested we could use this [Notion Notes Template](https://thomasfrank.notion.site/Notes-Template-58250a4b44ec4a29b61c922c147467b1) as our database.

I cloned the database and placed it under the Notion page I had given Pipedream access to. 

![Screenshot 2024-02-15 at 10 06 58 PM](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/22891582/33bf6b80-3a95-43af-9367-55fa3ed3babc)

Upon selecting the database and click on test, I encountered the following error:

```
Error
An error occurred while processing the audio file: Failed to read audio file metadata. The file format might be unsupported or corrupted, or the file might no longer exist at the specified file path (which is in temp storage). If you are using the Google Drive or OneDrive versions of this workflow and are currently setting it up, please try testing your 'download' step again in order to re-download the file into temp storage. Then test this step again. Learn more here: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#error-failed-to-read-audio-file-metadata

DETAILS
    at Object.getDuration (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:343:11)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1895:23)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)
``` 

This is my first encounter with your content, and everything was exceptionally well explained until the database selection step. I suspect this issue is related to that part. Could you offer any advice on what to do next?

Thank you for your help. If we can resolve this issue, I'll definitely subscribe to all your platforms and become a loyal follower. This automation is precisely what I've been searching for!

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
OneDrive

**Comment by TomFrankly** [comment]
@Alfrex92 you're saying this happened the moment you clicked on the database? Or did it happen when you did a test run? Typically this happens only after a test run fails.

Most often, this specific error happens because the audio file has been cleared out from the /tmp/ directory. If you try testing the OneDrive download step again, then test this final step, that might fix it.
