### ISSUE TITLE
Variety of error codes

### ISSUE THREAD

**Issue by mjrose514** [TomFrankly/pipedream-notion-voice-notes#71]
**Describe the bug**
I can't get past the last test phase. I tried last night and tonight and between the two I've gotten 3 different error messages. I can't remember the first two, but the current one is saying corrupted or not there... but it's there and fine. I did notice it's an m4a file. Not sure if that's causing a problem, but that's what is coming directly from my voice memos and I wouldn't know how to change it. 

"An error occurred while processing the audio file: Failed to read audio file metadata. The file format might be unsupported or corrupted, or the file might no longer exist at the specified file path (which is in temp storage). If you are using the Google Drive or OneDrive versions of this workflow and are currently setting it up, please try testing your 'download' step again in order to re-download the file into temp storage. Then test this step again. Learn more here: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#error-failed-to-read-audio-file-metadata

DETAILS
    at Object.getDuration (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:358:11)
    at Object.run (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1984:23)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)"

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google drive

**Have you tried updating your workflow?**
I have completely deleted and restarted. I've tried a new api key. I've updated my billing. I've redownloaded each and every try. I've tried changing the notion database. I've tried adding a different file and using that... Not sure what else I could change. 

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Only at the setting up and testing stage

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**
2/19/2024, 11:13:06 PM
Checking that file is under 300mb...

2/19/2024, 11:13:06 PM
File size is approximately 0.6mb.

2/19/2024, 11:13:06 PM
File is under the size limit. Continuing...

2/19/2024, 11:13:06 PM
Checking if the user set languages...

2/19/2024, 11:13:06 PM
No language set. Whisper will attempt to detect the language.

2/19/2024, 11:13:06 PM
File path of Google Drive file: /tmp/Clerbrook Golf RV Resort 2.m4a

2/19/2024, 11:13:06 PM
at Object.getDuration (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:340:12) at Object.run (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1984:23) at null.executeComponent (/var/task/launch_worker.js:294:22) at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)

2/19/2024, 11:13:06 PM
Attempting to clean up the /tmp/ directory...

2/19/2024, 11:13:06 PM
File /tmp/Clerbrook Golf RV Resort 2.m4a does not exist.

2/19/2024, 11:13:06 PM
Directory does not exist.

**Comment by mjrose514** [comment]
anyone?

**Comment by TomFrankly** [comment]
@mjrose514 could you try testing with this file? https://www.dropbox.com/scl/fi/htbnh86xvqevzznhzgej6/testaudio.m4a?rlkey=l4w8mhlqgds2khwjrllvekqbp&dl=0

You can see me successfully set up and test a new copy of the workflow from scratch using this file here: https://www.loom.com/share/c6db525dcb114145a1674d4c05855a75?sid=ea5dd995-4931-43a3-b79d-9d6b2ed6dcdb

Additionally, can you refresh the workflow builder page and make sure the final step is updated, as shown at 00:47 in the video?

**Comment by neusql** [comment]
m4a works! I was experiencing the same issue as mjrose514. it was a file format issue in the end. Incredible you can create something like this just after 1 year of programming Tom -a real inspiration. I've been learning on and off through CS50 and ChatGPT for 2 years and haven't gotten where you are.

**Comment by mjrose514** [comment]
I'm working with Google Drive. I have updated, started anew, uploaded your
file to google drive, and tried again and still getting errors.

**Comment by mjrose514** [comment]
How did you get yours to work? I've tried both formats and neither worked.

**Comment by TomFrankly** [comment]
@mjrose514 can you confirm that you've connected a credit card to your OpenAI account, added credits, generated a new API key after doing that, and are using that new API key in Pipedream?

If you're using my file and are following the video I posted above, this is the only other variation I can think of that would cause a failure. It has to be something happening on OpenAI's side.

**Comment by mjrose514** [comment]
I’ll check on the credits and such. But the video you sent was for Dropbox
not google drive so some of the things are different…

**Comment by TomFrankly** [comment]
@mjrose514 the only difference is that with Google Drive, you'll want to make sure you test the google_drive step again before re-testing the notion_voice_notes step.

This because the latter step clears temp storage on each run, so you need to download the file back into temp storage on subsequent tests.

**Comment by TomFrankly** [comment]
Fixed in the latest version: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow
