### ISSUE TITLE
Voice Notes not working

### ISSUE THREAD

**Issue by berchman** [TomFrankly/pipedream-notion-voice-notes#74]
Error
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.

DETAILS

Explain
    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:785:28)

**Comment by sahijsingh** [comment]
Getting the same error.

**Comment by sahijsingh** [comment]
I'm getting the same error.

**Comment by alexkeeley** [comment]
I'm also having the same issue with a nearly identical error code: 

Error
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.

DETAILS
    at Object.chunkFileAndTranscribe (file:///pipedream/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at Object.run (file:///pipedream/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)

**Comment by berchman** [comment]
Hi Thomas, yes, I'll give it a try again today.
For reference I was using the sample file you provided in the tut. So it's not the size of the file.
Anyhow, will try it again shortly and report back.
THANKS for your reply! 
Cheers,
Bert

**Comment by alexkeeley** [comment]
I have tried again and the issue is resolved. 

And as your help pages suggest: yes it was a billing issue (with the new "purchase credits upfront system" for API). 
I had not realised this when I generated a new key. 

I put some credit on my account, generated a new key and retested and all successful. 

Many thanks for your reply.

**Comment by berchman** [comment]
Likewise @TomFrankly my issue is resolved as well.
I actually ran into a permission error where I couldn't create a page in Notion, but I resolved that.

**Comment by friesenkevin** [comment]
Thank you!!! Worked, it was a funding issue for my API account.
