### ISSUE TITLE
Issue with Notion Voice Notes for Google Drive tutorial

### ISSUE THREAD

**Issue by friesenkevin** [TomFrankly/pipedream-notion-voice-notes#75]
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.  

  at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:785:28)

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google Drive

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update
Tried multiple times, billing info is correct, 

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Workflow doesn't work

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

**Comment by TomFrankly** [comment]
Hi @friesenkevin, please see the solutions in #74 and check if that helps!
