### ISSUE TITLE
summary extraction fails with `Cannot read properties of undefined`

### ISSUE THREAD

**Issue by YildirimYazganarikan** [TomFrankly/pipedream-notion-voice-notes#77]
**Describe the bug**
I started recieving such an error for a week now

![2024-03-18 20_25_59-VoiceWorkflowforVoiceSystem2 - Pipedream](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/61211465/6d66ad6e-a213-4eed-b20b-edb56e639480)

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**

Google Drive

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

yes

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**

it happens during normal, automated runs.

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

![2024-03-18 20_27_47-VoiceWorkflowforVoiceSystem2 - Pipedream](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/61211465/c1745dee-65d2-48f9-8a09-64e2bf83358f)

**Comment by TomFrankly** [comment]
@YildirimYazganarikan can you check that your ChatGPT Model field has a value in it? This error looks like it'd be thrown if that property is empty.

**Comment by toddlich** [comment]
Hi Tom, can you help me get back up and running. I am getting this PipeDream error in the audio notes to Notion build.

 Error
Failed to download file: getaddrinfo ENOTFOUND ud78r9s3t6c6s7afa545778b4100.dl.cloudstorageusercontent.com

DETAILS
    at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:316:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1885:5)
    at null.executeComponent (/var/task/launch_worker.js:287:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:786:28)

**Comment by TomFrankly** [comment]
@toddlich are you using Dropbox? This error might be happening because the file is no longer available, or in the case of Dropbox, they've terminated the public access link that is generated when you upload a new file. Dropbox only keeps those links around for a couple hours, unlike Google Drive/OneDrive 

(By "public access" I mean authenticated, external integrations in this case. Not actual public access)

I'd recommend trying to upload a new audio file and seeing if that works.
