### ISSUE TITLE
Language detection failed with error: Cannot read properties of undefined (reading 'completions')

### ISSUE THREAD

**Issue by jujus88** [TomFrankly/pipedream-notion-voice-notes#85]
**Which cloud storage app are you using? **Google Drive** 

**Have you tried updating your workflow?** **YES**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update 

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
It happens only when i need summary in Russian instead of English, when transcript is in Russian. It would make sense to leave it blanc, but in this case summary comes in English (and it works just fine).

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

Error
Language detection failed with error: Cannot read properties of undefined (reading 'completions')

DETAILS
    at Object.detectLanguage (file:///tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/helpers/translate-transcript.mjs:67:11)
    at Object.run (file:///tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:2547:29)
    at null.executeComponent (/var/task/launch_worker.js:288:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:788:28)
<img width="901" alt="Снимок экрана 2024-05-28 в 20 40 06" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/171075982/58d30bf0-556f-42ea-92f8-569a4e5fcbd9">

**Comment by ikk0** [comment]
Same issue here, happens for me too, even with other languages. It happens as soon as you specify a "Summary Language".

**Comment by HotBlaster** [comment]
Same for me, my note are correctly transcribed in Italian, but summary is in English.
If I add Italian as summary language, I get an error

**Comment by TomFrankly** [comment]
Hey all, I'm currently aware of this issue, but at the moment it requires a pretty intensive process to fix. I'll do my best to get a fix shipped when I can, but I have to finish some higher-priority items beforehand.

Thanks for understanding!

**Comment by eljarno** [comment]
Hello there ;-),

unfortunatly the issue is still present. Would be great if it could be fixed in near future.

Cheers
Jan

**Comment by TomFrankly** [comment]
@eljarno which cloud storage option are you using? I have a beta that might fix the issue I can send you, but I need to know which storage option you need.

**Comment by eljarno** [comment]
@TomFrankly currently I'm using OneDrive but I also tried it with GDrive. In both systems I had this issue. Looking forward hearing from you. Regards Jan

**Comment by TomFrankly** [comment]
@eljarno if you can use Google Drive for now, this template link will let you test the beta: https://pipedream.com/new?h=tch_Nxfyq0

Let me know if that fixes the issue!

**Comment by eljarno** [comment]
Great I will give it a try

**Comment by lag108** [comment]
@TomFrankly Hello. I have encountered the same error. If you leave the summary language field epmty everything is fine. But otherwise it results the error. Do you have the beta for drop box?

Thank you in advance!

**Comment by lag108** [comment]
@TomFrankly Hello. Thank you for reply. Here is some feedback, when I choose the "true" option on advanced settings I have this error poping up. I tried multiple times but still the same.
Type Error
Cannot read properties of undefined (reading 'toLowerCase')

**Comment by TomFrankly** [comment]
@lag108 thanks! I think I've got that fixed. If you refresh, you should see an Update button to update the action:

<img width="922" alt="Image" src="https://github.com/user-attachments/assets/9b4ad0bf-ecb3-4356-baa1-b40a23f9a818" />

After updating, you may need to click Refresh Fields after the last field in the Configure tab.

I just ran a successful test where I uploaded an English audio file and got a Spanish summary and transcript, along with the original English transcript:

![Image](https://github.com/user-attachments/assets/19053b3b-ba92-4fbe-8a57-c8caf2f74671)

![Image](https://github.com/user-attachments/assets/588cae0d-f01f-4381-92e7-cd8dd1aa5ec7)

![Image](https://github.com/user-attachments/assets/c37ec7f6-71d7-4b40-babc-f43bd92c4db4)

**Comment by lag108** [comment]
@TomFrankly Thank you! It helped. Now it works just fine. Translating the summary into other languages works. Thanks for the fix.

I noticed that in the beta, by default, you are using GPT-4o Mini instead of 3.5 Turbo. I’ve run a few tests as well. It seems like 4o Mini can sometimes be better, and it's cheaper too. Is there a situation in which 3.5 Turbo could still be better, in your experience?

**Comment by TomFrankly** [comment]
@lag108 glad it's working now!

I don't think there's any reason to use 3.5-turbo anymore. 4o-mini is significantly cheaper and a lot better as well.

**Comment by TomFrankly** [comment]
Fixed in the latest version: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow
