### ISSUE TITLE
Error PLEASE READ THIS ENTIRE ERROR MESSAGE. An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI.

### ISSUE THREAD

**Issue by 928Apache** [TomFrankly/pipedream-notion-voice-notes#86]
**Describe the bug**

An error occurred while attempting to split the file into chunks, or while sending the chunks to OpenAI.

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**

Dropbox

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

I have updated to the workflow.

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**

The issue is happening while I am testing the workflow. I also deployed the workflow and still get the same error.

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

at Object.chunkFileAndTranscribe (file:///pipedream/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:536:11)
    at Object.run (file:///pipedream/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:2351:23)
    at null.executeComponent (/var/task/launch_worker.js:288:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:788:28)

5/28/2024, 4:49:25 PM
Checking that file is under 300mb...

5/28/2024, 4:49:25 PM
File size is approximately 6.1mb.

5/28/2024, 4:49:25 PM
File is under the size limit. Continuing...

5/28/2024, 4:49:25 PM
Checking if the user set languages...

5/28/2024, 4:49:25 PM
User set transcript language to en.

5/28/2024, 4:49:25 PM
User set summary language to en.

5/28/2024, 4:49:25 PM
Setting the transcription service...

5/28/2024, 4:49:25 PM
Logging settings...

5/28/2024, 4:49:25 PM
Action Version::
No version detected
Audio File Chunk Size:
15
Chat Model:
gpt-3.5-turbo
Fail on no Duration:
false
Moderation Check:
true
Note Cost Property:
AI Cost
Note Duration Property:
Duration (Seconds)
Note Title Property:
Title
Summary Density:
2000
Summary Language:
en
Summary Options
[4]
0:
Summary
1:
Main Points
2:
Action Items
3:
Follow-up Questions
Temperature::
0.2 (default)
Transcript Language:
en
Transcription Service:
OpenAI
Verbosity:
Low
5/28/2024, 4:49:25 PM
Setup stage duration: 3.24017ms

5/28/2024, 4:49:25 PM
Total duration so far: 3.24017ms (0.00324017 seconds)

5/28/2024, 4:49:26 PM
Downloaded file to tmp storage:

5/28/2024, 4:49:26 PM
{ file_name: 'Sample Audio File v5.mp3', path: '/tmp/sample audio file v5.mp3', mime: '.mp3' }

5/28/2024, 4:49:26 PM
File path of Dropbox file: /tmp/sample audio file v5.mp3

5/28/2024, 4:49:26 PM
Successfully got duration: 256 seconds

5/28/2024, 4:49:26 PM
Download stage duration: 364.067967ms (0.364067967 seconds)

5/28/2024, 4:49:26 PM
Total duration so far: 367.308137ms (0.367308137 seconds)

5/28/2024, 4:49:26 PM
Using OpenAI's Whisper service for transcription.

5/28/2024, 4:49:26 PM
Chunking file: /tmp/sample audio file v5.mp3

5/28/2024, 4:49:26 PM
Full file size: 5.86456298828125mb. Chunk size: 15mb. Expected number of chunks: 1. Commencing chunking...

5/28/2024, 4:49:26 PM
Created 1 chunk: /tmp/chunks-2h7LRfToIdRok1ViFq5yRWDfX8S/chunk-000.mp3

5/28/2024, 4:49:26 PM
Chunks created successfully. Transcribing chunks: chunk-000.mp3

5/28/2024, 4:49:26 PM
Transcribing file: chunk-000.mp3

5/28/2024, 4:50:54 PM
Encountered error from OpenAI: Connection error.

5/28/2024, 4:50:54 PM
Status code: undefined

5/28/2024, 4:50:54 PM
Error name: Error

5/28/2024, 4:50:54 PM
Error headers: undefined

5/28/2024, 4:50:54 PM
Encountered a recoverable error. Retrying...

5/28/2024, 4:50:54 PM
Retrying transcription for chunk-000.mp3 due to error: Error: Connection error.

5/28/2024, 4:50:56 PM
Transcribing file: chunk-000.mp3

5/28/2024, 4:52:25 PM
Encountered error from OpenAI: Connection error.

5/28/2024, 4:52:25 PM
Status code: undefined

5/28/2024, 4:52:25 PM
Error name: Error

5/28/2024, 4:52:25 PM
Error headers: undefined

5/28/2024, 4:52:25 PM
Encountered a recoverable error. Retrying...

5/28/2024, 4:52:25 PM
Retrying transcription for chunk-000.mp3 due to error: Error: Connection error.

5/28/2024, 4:52:28 PM
Transcribing file: chunk-000.mp3

5/28/2024, 4:53:57 PM
Encountered error from OpenAI: Connection error.

5/28/2024, 4:53:57 PM
Status code: undefined

5/28/2024, 4:53:57 PM
Error name: Error

5/28/2024, 4:53:57 PM
Error headers: undefined

5/28/2024, 4:53:57 PM
Encountered a recoverable error. Retrying...

5/28/2024, 4:53:57 PM
Retrying transcription for chunk-000.mp3 due to error: Error: Connection error.

5/28/2024, 4:54:03 PM
Transcribing file: chunk-000.mp3

5/28/2024, 4:55:33 PM
Encountered error from OpenAI: Connection error.

5/28/2024, 4:55:33 PM
Status code: undefined

5/28/2024, 4:55:33 PM
Error name: Error

5/28/2024, 4:55:33 PM
Error headers: undefined

5/28/2024, 4:55:33 PM
Encountered a recoverable error. Retrying...

5/28/2024, 4:55:33 PM
Attempting to clean up the /tmp/ directory...

5/28/2024, 4:55:33 PM
Cleaning up /tmp/chunks-2h7LRfToIdRok1ViFq5yRWDfX8S...

5/28/2024, 4:55:33 PM
ACTIVE_HANDLE
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: ChildProcess, Learn more: https://pipedream.com/docs/code/nodejs/async/)

Copy

**Comment by TomFrankly** [comment]
Fixed in the latest version: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow
