### ISSUE TITLE
Suddenly getting "Failed to download file" error. tried rebuilding new workflow from scratch and repeated issue.

### ISSUE THREAD

**Issue by richtack** [TomFrankly/pipedream-notion-voice-notes#87]
**Describe the bug**
The workflow stopped working after working successfully for months. Now getting a "Failed to download file" issue. after trying to fix and searching pipe dream support, I decided to rebuild a whole new workflow from scratch, and the error repeated on the new project. 

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Dropbox

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update
Yes

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Both. I get an error message when I upload an audio file to the dropbox folder.

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

Error
Failed to download file: getaddrinfo ENOTFOUND ud78r9s3t6c6s7afa545778b4100.dl.cloudstorageusercontent.com
DETAILS
    at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:2309:5)
    at null.executeComponent (/var/task/launch_worker.js:288:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:788:28)

**Comment by TomFrankly** [comment]
@richtack can you share a screenshot of your Dropbox trigger tab? I'd like to check that your Include Link option is set to True: 
![CleanShot 2024-06-11 at 19 32 44@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/1e9f8be4-a2b8-489c-a808-6050fbc28f45)

Can you also try re-uploading your audio file with a new name? Dropbox specifically has a quirk where it deletes the download URL that Pipedream uses after about 2 hours. After that, there's no way for Pipedream to access that file again, that I know of.

**Comment by richtack** [comment]
Thank you for getting back to me directly!

As you'll see by the screenshot, Include Link is set to True. 
![CleanShot 2024-06-12 at 08 05 26@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/10813539/5b852706-bb4e-415a-9900-9988a727bbdd)

This is likely not helpful, but here's a screenshot of the log.
![CleanShot 2024-06-14 at 06 33 33@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/10813539/a7c4b519-b7b3-4a13-8250-c526ad1c2f8c)

Here's the full error I get when I try uploading a new file to the dropbox folder.

![CleanShot 2024-06-14 at 06 39 57@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/10813539/e33be80c-82d1-47cd-8789-7a1f4ac114f7)

Too much information, I'm sure! But really appreciate this. Happy to support you in this effort!

**Comment by TomFrankly** [comment]
@richtack in your Details page, can you check that your version is 0.7.30?

![CleanShot 2024-06-14 at 10 37 29@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/9fba86c5-f43f-4416-8ee1-3c19d99aa817)

It may also be easiest to recreate the workflow from my template links here: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow - this will ensure you've got the latest version!

**Comment by richtack** [comment]
just checked - yes, it's 0.7.30. BTW, when this problem started, I disabled my original workflow and recreated a second instance per the original instructions and the same issue replicated. I do think it started after Pipedream updated something on their platform? I wish I knew more to hunt that down.
