### ISSUE TITLE
 error in google_drive_download

### ISSUE THREAD

**Issue by mdessl** [TomFrankly/pipedream-notion-voice-notes#89]
**Describe the bug**
the first step works but i am getting an error in google_drive_download. the error message is provided below. 

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google Drive

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update
yes, i have.

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
both

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**
    at Gaxios._request (/pipedream/dist/code/9a6cd4479bf6f576ba045b4f054c08a480fe1177ff85305fbc524a1505b6f546/node_modules/.pnpm/gaxios@4.3.3/node_modules/gaxios/build/src/gaxios.js:129:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at OAuth2Client.requestAsync (/pipedream/dist/code/9a6cd4479bf6f576ba045b4f054c08a480fe1177ff85305fbc524a1505b6f546/node_modules/.pnpm/google-auth-library@7.14.1/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
    at Object.getFile (file:///pipedream/dist/code/9a6cd4479bf6f576ba045b4f054c08a480fe1177ff85305fbc524a1505b6f546/node_modules/.pnpm/@pipedream+google_drive@0.8.1/node_modules/@pipedream/google_drive/google_drive.app.mjs:778:9)
    at Object.run (file:///pipedream/dist/code/9a6cd4479bf6f576ba045b4f054c08a480fe1177ff85305fbc524a1505b6f546/component.mjs:56:26)
    at null.executeComponent (/var/task/launch_worker.js:288:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:788:28)

**Comment by TomFrankly** [comment]
@mdessl is there error text as well? I don't see a report of what the actual problem is here.

Also, can you make sure your download step has "{{steps}}" (no quotes) in the second property?

![CleanShot 2024-06-11 at 17 39 39@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/92198312-994d-4196-a6ab-945eb985f22f)

**Comment by mdessl** [comment]
Here is how it looks for me when I run test in google_drive_download

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/49913272/7298c929-0124-435d-833f-4d0d3e01cf30)

Thanks!

**Comment by TomFrankly** [comment]
@mdessl I'd recommend creating a new copy of the workflow with the template link here: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow

I just tried it out and didn't get this error. (I also made sure to test my trigger step first – do that if you haven't already)

**Comment by mdessl** [comment]
Oh amazing! I started a new one and it's working now. Thank you
