### ISSUE TITLE
Error due to new version of natural

### ISSUE THREAD

**Issue by Safrone** [TomFrankly/pipedream-notion-voice-notes#91]
**Describe the bug**

when running the test according to the guide I receive this error:

```
TypeError
Cannot read properties of undefined (reading 'map')

Details
    at SentenceTokenizer.replaceAbbreviations (/tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/node_modules/.pnpm/natural@8.0.0/node_modules/natural/lib/natural/tokenizers/sentence_tokenizer.js:67:55)
    at SentenceTokenizer.tokenize (/tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/node_modules/.pnpm/natural@8.0.0/node_modules/natural/lib/natural/tokenizers/sentence_tokenizer.js:152:26)
    at Object.makeParagraphs (file:///tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:1386:37)
    at Object.run (file:///tmp/__pdg__/dist/code/16157ccb517312283553eaaa945076926a83e8862411456e6deb94d0e9fdf944/code/Notion-Voice-Notes.mjs:2494:21)
    at null.executeComponent (/var/task/launch_worker.js:292:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:792:28)
```

I did a little digging into [natural](https://www.npmjs.com/package/natural?activeTab=code) and it looks like they just released version 8.0.0 4 hours ago which includes a rewrite of the SentenceTokenizer which seems to break if [you do not pass the constructor abbreviations](https://github.com/NaturalNode/natural/commit/fcb696cae1a4be5fda64d8c8f94225eed9971af6#diff-ad7918a8ed684f0c5bd9fc15cf5688db1a1626ea4f1cedaa42d71f4b49caaadbR42)
[here](https://github.com/NaturalNode/natural/commit/fcb696cae1a4be5fda64d8c8f94225eed9971af6#diff-ad7918a8ed684f0c5bd9fc15cf5688db1a1626ea4f1cedaa42d71f4b49caaadbR67)
 
the quick fix is probably pinning a max version natural for now

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google Drive

**Have you tried updating your workflow?**
Happening on a new run of the test

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
testing but probably happens in the normal runs too if natural@8.0.0 is installed

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

**Comment by Safrone** [comment]
made an issue on natural as well: https://github.com/NaturalNode/natural/issues/752

**Comment by TomFrankly** [comment]
Hey @Safrone, thanks for flagging this! I can see the natural team marked the bug fixed on their end; have you been able to use the automation since then?
