### ISSUE TITLE
Cannot read properties of undefined (reading 'file')

### ISSUE THREAD

**Issue by CassieMaeC** [TomFrankly/pipedream-notion-voice-notes#96]
**Describe the bug**
I was able to set up and deploy with YouTube instructions, but no voice file has worked after that.
Anytime I try a new audio file, nothing happens in pipedream, and I get that error message in the log.

Using OneDrive

**Have you tried updating your workflow?**
Yes, I've only been working on it today with the YouTube instructions

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Happens during normal automated runs. 

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**
TypeError: Cannot read properties of undefined (reading 'file')
at Object.isItemRelevant (file:///var/task/user/sources/new-file-in-folder/new-file-in-folder.mjs:30:27)
at Object._processEventsFromDeltaLink (file:///var/task/user/sources/common/base.mjs:165:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.run (file:///var/task/user/sources/common/base.mjs:294:3)
at async /var/task/index.js:122:11
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async exports.main [as handler] (/var/task/index.js:60:20)
**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**

**Comment by TomFrankly** [comment]
Fixed in the latest version: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow
